// <auto-generated>
//   This file is generated from Resources.resx. Do not edit directly.
// </auto-generated>

using System.Globalization;
using System.Resources;

namespace KarteDomainService.Resources;

internal static class Resources
{
    private static readonly ResourceManager _rm =
        new("KarteDomainService.Resources.Resources", typeof(Resources).Assembly);

    private static string GetString(string name) =>
        _rm.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    // エラーレスポンスメッセージ
    internal static string E400000 => GetString("E400000");
    internal static string E404000 => GetString("E404000");
    internal static string E409000 => GetString("E409000");
    internal static string E500001 => GetString("E500001");

    // 業務エラーメッセージ
    internal static string E_PATIENT_ID_REQUIRED       => GetString("E_PATIENT_ID_REQUIRED");
    internal static string E_REQUEST_VALIDATION_FAILED => GetString("E_REQUEST_VALIDATION_FAILED");

    // Data Annotations の ErrorMessage に使用するコンパイル時定数
    // （属性引数は定数のみ受け付けるため static readonly ではなく const で定義する）
    internal const string C_PATIENT_ID_REQUIRED = "患者IDは必須です。";

    // ログメッセージ
    internal static string LOG_UNEXPECTED_ERROR          => GetString("LOG_UNEXPECTED_ERROR");
    internal static string LOG_CHIEF_COMPLAINT_GET       => GetString("LOG_CHIEF_COMPLAINT_GET");
    internal static string LOG_CHIEF_COMPLAINT_NOT_FOUND => GetString("LOG_CHIEF_COMPLAINT_NOT_FOUND");
    internal static string LOG_VITAL_INFO_GET            => GetString("LOG_VITAL_INFO_GET");
    internal static string LOG_VITAL_INFO_NOT_FOUND      => GetString("LOG_VITAL_INFO_NOT_FOUND");
    internal static string LOG_PRESCRIPTION_ORDER_GET    => GetString("LOG_PRESCRIPTION_ORDER_GET");
}
