import {
  Pill,
  Syringe,
  Scissors,
  BookOpen,
  FlaskConical,
  Activity,
  Eye,
  Stethoscope,
  Microscope,
  Bug,
  Clipboard,
  Users,
  Heart,
  Zap,
  Droplets,
  Utensils,
  Wind,
  BedDouble,
  Baby,
  Dumbbell,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { OrderType } from "@/front_bff_shared/features/orders/_shared/types/order.type";

export interface OrderTypeConfig {
  label: string;
  icon: LucideIcon;
  color: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
}

export const ORDER_TYPES: Record<OrderType, OrderTypeConfig> = {
  prescription: {
    label: "処方",
    icon: Pill,
    color: "bg-purple-600",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    borderColor: "border-purple-200 dark:border-purple-800",
    textColor: "text-purple-700 dark:text-purple-300",
  },
  injection: {
    label: "注射",
    icon: Syringe,
    color: "bg-emerald-600",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/20",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    textColor: "text-emerald-700 dark:text-emerald-300",
  },
  procedure: {
    label: "処置",
    icon: Scissors,
    color: "bg-sky-600",
    bgColor: "bg-sky-50 dark:bg-sky-950/20",
    borderColor: "border-sky-200 dark:border-sky-800",
    textColor: "text-sky-700 dark:text-sky-300",
  },
  guidance: {
    label: "指導",
    icon: BookOpen,
    color: "bg-amber-600",
    bgColor: "bg-amber-50 dark:bg-amber-950/20",
    borderColor: "border-amber-200 dark:border-amber-800",
    textColor: "text-amber-700 dark:text-amber-300",
  },
  lab: {
    label: "検査（血液・尿等）",
    icon: FlaskConical,
    color: "bg-orange-600",
    bgColor: "bg-orange-50 dark:bg-orange-950/20",
    borderColor: "border-orange-200 dark:border-orange-800",
    textColor: "text-orange-700 dark:text-orange-300",
  },
  physiology: {
    label: "生理検査",
    icon: Activity,
    color: "bg-red-600",
    bgColor: "bg-red-50 dark:bg-red-950/20",
    borderColor: "border-red-200 dark:border-red-800",
    textColor: "text-red-700 dark:text-red-300",
  },
  endoscopy: {
    label: "内視鏡",
    icon: Eye,
    color: "bg-teal-600",
    bgColor: "bg-teal-50 dark:bg-teal-950/20",
    borderColor: "border-teal-200 dark:border-teal-800",
    textColor: "text-teal-700 dark:text-teal-300",
  },
  imaging: {
    label: "画像検査",
    icon: Stethoscope,
    color: "bg-blue-600",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    borderColor: "border-blue-200 dark:border-blue-800",
    textColor: "text-blue-700 dark:text-blue-300",
  },
  pathology: {
    label: "病理",
    icon: Microscope,
    color: "bg-indigo-600",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/20",
    borderColor: "border-indigo-200 dark:border-indigo-800",
    textColor: "text-indigo-700 dark:text-indigo-300",
  },
  microbiology: {
    label: "細菌",
    icon: Bug,
    color: "bg-pink-600",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    borderColor: "border-pink-200 dark:border-pink-800",
    textColor: "text-pink-700 dark:text-pink-300",
  },
  general: {
    label: "汎用",
    icon: Clipboard,
    color: "bg-slate-600",
    bgColor: "bg-slate-50 dark:bg-slate-950/20",
    borderColor: "border-slate-200 dark:border-slate-800",
    textColor: "text-slate-700 dark:text-slate-300",
  },
  rehabilitation: {
    label: "リハビリ",
    icon: Users,
    color: "bg-lime-600",
    bgColor: "bg-lime-50 dark:bg-lime-950/20",
    borderColor: "border-lime-200 dark:border-lime-800",
    textColor: "text-lime-700 dark:text-lime-300",
  },
  transfusion: {
    label: "輸血",
    icon: Heart,
    color: "bg-rose-600",
    bgColor: "bg-rose-50 dark:bg-rose-950/20",
    borderColor: "border-rose-200 dark:border-rose-800",
    textColor: "text-rose-700 dark:text-rose-300",
  },
  surgery: {
    label: "手術",
    icon: Zap,
    color: "bg-violet-600",
    bgColor: "bg-violet-50 dark:bg-violet-950/20",
    borderColor: "border-violet-200 dark:border-violet-800",
    textColor: "text-violet-700 dark:text-violet-300",
  },
  dialysis: {
    label: "透析",
    icon: Droplets,
    color: "bg-cyan-600",
    bgColor: "bg-cyan-50 dark:bg-cyan-950/20",
    borderColor: "border-cyan-200 dark:border-cyan-800",
    textColor: "text-cyan-700 dark:text-cyan-300",
  },
  nutrition: {
    label: "栄養",
    icon: Utensils,
    color: "bg-green-600",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    borderColor: "border-green-200 dark:border-green-800",
    textColor: "text-green-700 dark:text-green-300",
  },
  respiratory: {
    label: "呼吸器",
    icon: Wind,
    color: "bg-blue-600",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    borderColor: "border-blue-200 dark:border-blue-800",
    textColor: "text-blue-700 dark:text-blue-300",
  },
  bed: {
    label: "ベッド",
    icon: BedDouble,
    color: "bg-gray-600",
    bgColor: "bg-gray-50 dark:bg-gray-950/20",
    borderColor: "border-gray-200 dark:border-gray-800",
    textColor: "text-gray-700 dark:text-gray-300",
  },
  surgeryProcedure: {
    label: "手術処置",
    icon: Scissors,
    color: "bg-yellow-700",
    bgColor: "bg-yellow-50 dark:bg-yellow-950/20",
    borderColor: "border-yellow-200 dark:border-yellow-800",
    textColor: "text-yellow-700 dark:text-yellow-300",
  },
  neonatal: {
    label: "新生児",
    icon: Baby,
    color: "bg-pink-600",
    bgColor: "bg-pink-50 dark:bg-pink-950/20",
    borderColor: "border-pink-200 dark:border-pink-800",
    textColor: "text-pink-700 dark:text-pink-300",
  },
  physicalTherapy: {
    label: "物理療法",
    icon: Dumbbell,
    color: "bg-red-600",
    bgColor: "bg-red-50 dark:bg-red-950/20",
    borderColor: "border-red-200 dark:border-red-800",
    textColor: "text-red-700 dark:text-red-300",
  },
};
