import type { Order, Allergy, Contraindication } from '../types';

const mockAllergies: Allergy[] = [
  {
    id: 'a1',
    component: 'ペニシリン系抗生物質',
    category: '薬剤',
    severity: '重度',
    symptoms: '呼吸困難、発疹',
    registeredDate: '2024/03/15',
    source: '本人申告'
  },
  {
    id: 'a2',
    component: '造影剤',
    category: '薬剤',
    severity: '中等度',
    symptoms: '発疹、かゆみ',
    registeredDate: '2024/06/20',
    source: '医師記録'
  },
  {
    id: 'a3',
    component: 'ロキソニン',
    category: '薬剤',
    severity: '中等度',
    symptoms: '蕁麻疹、胃痛',
    registeredDate: '2023/11/10',
    source: '本人申告'
  },
  {
    id: 'a4',
    component: 'ヨード',
    category: '薬剤',
    severity: '軽度',
    symptoms: '皮膚発赤',
    registeredDate: '2024/01/20',
    source: '医師記録'
  },
  {
    id: 'a5',
    component: 'エビ・カニ',
    category: '食事',
    severity: '重度',
    symptoms: 'アナフィラキシー',
    registeredDate: '2023/05/10',
    source: '本人申告'
  },
  {
    id: 'a6',
    component: '花粉',
    category: '環境',
    severity: '軽度',
    symptoms: 'くしゃみ、鼻水',
    registeredDate: '2024/02/15',
    source: '本人申告'
  },
  {
    id: 'a7',
    component: 'ラテックス',
    category: 'ラテックス',
    severity: '中等度',
    symptoms: '接触性皮膚炎',
    registeredDate: '2023/08/22',
    source: '医師記録'
  },
  {
    id: 'a8',
    component: 'ニッケル',
    category: '金属',
    severity: '軽度',
    symptoms: '皮膚かゆみ',
    registeredDate: '2024/01/05',
    source: '本人申告'
  }
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-002',
    status: '受付済',
    urgency: '緊急',
    patientId: 'P00012346',
    patientName: '佐藤 花子',
    patientKana: 'サトウ ハナコ',
    gender: '女',
    birthDate: '1978/08/22',
    age: 47,
    orderType: '検体検査',
    examinationType: '検体検査',
    content: '血液検査（CBC、生化学、凝固）',
    visualIndicator: [
      {
        tubeType: '紫キャップ',
        tubeColor: '#8B5CF6'
      },
      {
        tubeType: '黄キャップ',
        tubeColor: '#EAB308'
      },
      {
        tubeType: '水色キャップ',
        tubeColor: '#06B6D4'
      }
    ],
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    attendingDoctor: '佐々木医師',
    ward: '外来B',
    roomNumber: '採血室',
    orderDate: '2025/10/15',
    receivedAt: '2025/10/15 08:45',
    acceptedAt: '2025/10/15 09:30',
    acceptedBy: '看護師A',
    scheduledTime: '09:00',
    labTestLocation: '院内',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 08:45', updatedBy: '佐々木医師' },
      { status: '受付済', timestamp: '2025/10/15 09:30', updatedBy: '看護師A' }
    ]
  },
  {
    id: 'ORD-003',
    status: '実施済',
    patientId: 'P00012347',
    patientName: '鈴木 一郎',
    patientKana: 'スズキ イチロウ',
    gender: '男',
    birthDate: '1990/12/10',
    age: 34,
    orderType: 'リハビリ',
    content: '理学療法（腰部）30分',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '整形外科',
    attendingDoctor: '山本医師',
    ward: '外来C',
    roomNumber: 'リハ室2',
    receivedAt: '2025/10/15 09:30',
    acceptedAt: '2025/10/15 10:00',
    implementedAt: '2025/10/15 10:15',
    implementedBy: '理学療法士A',
    implementationNotes: '腰部ストレッチング、温熱療法実施。可動域改善あり。',
    scheduledTime: '10:00',
    urgency: '至急',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 09:30', updatedBy: '山本医師' },
      { status: '受付済', timestamp: '2025/10/15 10:00', updatedBy: '看護師B' },
      { status: '実施済', timestamp: '2025/10/15 10:15', updatedBy: '理学療法士A' }
    ]
  },
  {
    id: 'ORD-004',
    status: '指示受済',
    patientId: 'P00012348',
    patientName: '田中 美咲',
    patientKana: 'タナカ ミサキ',
    gender: '女',
    birthDate: '2000/03/05',
    age: 25,
    orderType: '画像検査',
    examinationType: '画像検査',
    content: '胸部CT検査（造影あり）',
    allergies: [mockAllergies[1]],
    hasAllergies: true,
    location: '外来',
    department: '内科',
    attendingDoctor: '鈴木医師',
    ward: '外来A',
    roomNumber: '放射線室',
    receivedAt: '2025/10/15 10:20',
    imageTestType: 'CT',
    consentRequired: true,
    consentObtained: true,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 10:20', updatedBy: '鈴木医師' }
    ]
  },
  {
    id: 'ORD-005',
    status: '実施済',
    patientId: 'P00012349',
    patientName: '高橋 健太',
    patientKana: 'タカハシ ケンタ',
    gender: '男',
    birthDate: '1955/11/30',
    age: 69,
    orderType: '栄養指導',
    content: '栄養指導（糖尿病食事療法）',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    attendingDoctor: '佐々木医師',
    ward: '外来B',
    roomNumber: '栄養指導室',
    receivedAt: '2025/10/15 07:45',
    acceptedAt: '2025/10/15 08:00',
    implementedAt: '2025/10/15 08:30',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 07:45', updatedBy: '佐々木医師' },
      { status: '実施済', timestamp: '2025/10/15 08:30', updatedBy: '管理栄養士A' }
    ]
  },
  {
    id: 'ORD-006',
    status: '採取済',
    patientId: 'P00012350',
    patientName: '伊藤 幸子',
    patientKana: 'イトウ サチコ',
    gender: '女',
    birthDate: '1948/03/12',
    age: 77,
    orderType: '検体検査',
    examinationType: '検体検査',
    content: '尿検査（尿沈渣、生化学）',
    visualIndicator: {
      tubeType: '黄キャップ',
      tubeColor: '#EAB308'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '泌尿器科',
    attendingDoctor: '中山医師',
    ward: '外来D',
    roomNumber: '採尿室',
    receivedAt: '2025/10/15 09:00',
    acceptedAt: '2025/10/15 09:15',
    acceptedBy: '看護師C',
    implementedAt: '2025/10/15 09:30',
    implementedBy: '看護師C',
    implementationNotes: '採尿完了。検体検査室へ提出予定。',
    scheduledTime: '09:15',
    labTestLocation: '院内',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 09:00', updatedBy: '中山医師' },
      { status: '受付済', timestamp: '2025/10/15 09:15', updatedBy: '看護師C' },
      { status: '採取済', timestamp: '2025/10/15 09:30', updatedBy: '看護師C' }
    ]
  },
  {
    id: 'ORD-007',
    status: '出庫済',
    patientId: 'P00012351',
    patientName: '渡辺 次郎',
    patientKana: 'ワタナベ ジロウ',
    gender: '男',
    birthDate: '1942/01/25',
    age: 83,
    orderType: '注射',
    content: 'ソルコーテフ100mg 静脈注射',
    visualIndicator: {
      medicationType: '注射剤',
      medicationForm: 'バイアル（透明液）'
    },
    allergies: [],
    hasAllergies: false,
    contraindications: [
      {
        id: 'c1',
        type: '禁忌',
        content: '腎機能障害（eGFR<30）',
        reason: '本剤は腎排泄型のため、重度腎機能障害患者では血中濃度が上昇し副作用リスクが高まる',
        registeredDate: '2024/08/10',
        source: '主治医記録'
      },
      {
        id: 'c2',
        type: '特記事項',
        content: '高血圧症治療中（降圧剤服用中）',
        reason: 'ステロイド投与により血圧上昇の可能性あり。投与後の血圧モニタリング必要',
        registeredDate: '2024/08/10',
        source: '主治医記録'
      }
    ],
    hasContraindications: true,
    location: '外来',
    department: '整形外科',
    attendingDoctor: '山本医師',
    ward: '外来C',
    roomNumber: '処置室2',
    receivedAt: '2025/10/15 14:00',
    implementedAt: '2025/10/15 14:30',
    implementedBy: '看護師D',
    implementationNotes: '薬剤部より出庫完了。投与準備中。',
    scheduledTime: '14:30',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 14:00', updatedBy: '山本医師' },
      { status: '出庫済', timestamp: '2025/10/15 14:30', updatedBy: '看護師D' }
    ]
  },
  {
    id: 'ORD-008',
    status: '受付済',
    patientId: 'P00012352',
    patientName: '中村 春香',
    patientKana: 'ナカムラ ハルカ',
    gender: '女',
    birthDate: '1995/05/12',
    age: 30,
    orderType: '生理検査',
    examinationType: '生理検査',
    content: '心電図検査',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    attendingDoctor: '田中医師',
    ward: '外来A',
    roomNumber: '検査室1',
    receivedAt: '2025/10/15 10:45',
    acceptedAt: '2025/10/15 11:00',
    acceptedBy: '看護師B',
    physiologicalTestType: '心電図',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 10:45', updatedBy: '田中医師' },
      { status: '受付済', timestamp: '2025/10/15 11:00', updatedBy: '看護師B' }
    ]
  },
  {
    id: 'ORD-009',
    status: '受付済',
    patientId: 'P00012353',
    patientName: '小林 健',
    patientKana: 'コバヤシ ケン',
    gender: '男',
    birthDate: '1972/09/18',
    age: 53,
    orderType: '内視鏡検査',
    examinationType: '内視鏡検査',
    endoscopyDetails: '上部消化管内視鏡検査（生検あり）',
    content: '上部消化管内視鏡検査',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 11:00',
    acceptedAt: '2025/10/15 11:30',
    acceptedBy: '看護師C',
    consentRequired: true,
    consentObtained: true
  },
  {
    id: 'ORD-010',
    status: '指示受済',
    patientId: 'P00012354',
    patientName: '松本 恵子',
    patientKana: 'マツモト ケイコ',
    gender: '女',
    birthDate: '1988/02/28',
    age: 37,
    orderType: '内視鏡検査',
    examinationType: '内視鏡検査',
    endoscopyDetails: '大腸内視鏡検査',
    content: '大腸内視鏡検査',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 12:15',
    consentRequired: true,
    consentObtained: false
  },
  {
    id: 'ORD-011',
    status: '開始済',
    patientId: 'P00012355',
    patientName: '加藤 隆',
    patientKana: 'カトウ タカシ',
    gender: '男',
    birthDate: '1960/11/05',
    age: 64,
    orderType: '処置',
    content: '関節穿刺（右膝）',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '整形外科',
    receivedAt: '2025/10/15 11:45',
    acceptedAt: '2025/10/15 12:00',
    acceptedBy: '看護師A',
    implementedAt: '2025/10/15 13:05',
    implementedBy: '山本医師',
    implementationNotes: '処置開始。関節液を採取中。',
    scheduledTime: '13:00',
    consentRequired: true,
    consentObtained: true,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 11:45', updatedBy: '山本医師' },
      { status: '受付済', timestamp: '2025/10/15 12:00', updatedBy: '看護師A' },
      { status: '開始済', timestamp: '2025/10/15 13:05', updatedBy: '山本医師' }
    ]
  },
  {
    id: 'ORD-012',
    status: '実施済',
    patientId: 'P00012345',
    patientName: '山田 太郎',
    patientKana: 'ヤマダ タロウ',
    gender: '男',
    birthDate: '1965/04/15',
    age: 60,
    orderType: '検体検査',
    examinationType: '検体検査',
    content: '血液検査（肝機能）',
    visualIndicator: {
      tubeType: '黄キャップ',
      tubeColor: '#EAB308'
    },
    allergies: [mockAllergies[0], mockAllergies[2], mockAllergies[3]],
    hasAllergies: true,
    location: '外来',
    department: '内科',
    attendingDoctor: '田中医師',
    ward: '外来A',
    roomNumber: '採血室',
    receivedAt: '2025/10/15 08:15',
    acceptedAt: '2025/10/15 08:30',
    implementedAt: '2025/10/15 08:45',
    implementedBy: '臨床検査技師A',
    implementationNotes: '採血実施。検体検査室へ提出済み。',
    scheduledTime: '08:30',
    labTestLocation: '院外',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 08:15', updatedBy: '田中医師' },
      { status: '受付済', timestamp: '2025/10/15 08:30', updatedBy: '看護師A' },
      { status: '実施済', timestamp: '2025/10/15 08:45', updatedBy: '臨床検査技師A' }
    ]
  },
  {
    id: 'ORD-013',
    status: '受付済',
    patientId: 'P00012345',
    patientName: '山田 太郎',
    patientKana: 'ヤマダ タロウ',
    gender: '男',
    birthDate: '1965/04/15',
    age: 60,
    orderType: '画像検査',
    examinationType: '画像検査',
    content: '腹部エコー検査',
    allergies: [mockAllergies[0], mockAllergies[2], mockAllergies[3]],
    hasAllergies: true,
    location: '外来',
    department: '内科',
    attendingDoctor: '田中医師',
    ward: '外来A',
    roomNumber: '超音波室',
    receivedAt: '2025/10/15 08:50',
    acceptedAt: '2025/10/15 09:00',
    acceptedBy: '看護師B',
    scheduledTime: '11:00',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 08:50', updatedBy: '田中医師' },
      { status: '受付済', timestamp: '2025/10/15 09:00', updatedBy: '看護師B' }
    ]
  },
  {
    id: 'ORD-014',
    status: '指示受済',
    patientId: 'P00012345',
    patientName: '山田 太郎',
    patientKana: 'ヤマダ タロウ',
    gender: '男',
    birthDate: '1965/04/15',
    age: 60,
    orderType: '注射',
    content: 'ビタミンB12注射',
    visualIndicator: {
      medicationType: '注射剤',
      medicationForm: 'アンプル（赤色液）'
    },
    allergies: [mockAllergies[0], mockAllergies[2], mockAllergies[3]],
    hasAllergies: true,
    location: '外来',
    department: '内科',
    attendingDoctor: '田中医師',
    ward: '外来A',
    roomNumber: '診察室1',
    receivedAt: '2025/10/15 09:20',
    scheduledTime: '13:00',
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 09:20', updatedBy: '田中医師' }
    ]
  },
  {
    id: 'ORD-015',
    status: '指示受済',
    patientId: 'P00012356',
    patientName: '木村 良子',
    patientKana: 'キムラ ヨシコ',
    gender: '女',
    birthDate: '1980/06/10',
    age: 45,
    orderType: '検体検査',
    examinationType: '検体検査',
    content: '凝固系検査（PT、APTT）',
    visualIndicator: {
      tubeType: '水色キャップ',
      tubeColor: '#06B6D4'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 13:00',
    labTestLocation: '院内'
  },
  {
    id: 'ORD-016',
    status: '受付済',
    patientId: 'P00012357',
    patientName: '斎藤 明',
    patientKana: 'サイトウ アキラ',
    gender: '男',
    birthDate: '1952/03/22',
    age: 73,
    orderType: '検体検査',
    examinationType: '検体検査',
    content: '血糖検査',
    visualIndicator: {
      tubeType: '灰色キャップ',
      tubeColor: '#6B7280'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 13:15',
    acceptedAt: '2025/10/15 13:20',
    acceptedBy: '看護師B',
    labTestLocation: '院外'
  },
  {
    id: 'ORD-017',
    status: '指示受済',
    patientId: 'P00012358',
    patientName: '前田 麻美',
    patientKana: 'マエダ アサミ',
    gender: '女',
    birthDate: '1993/11/08',
    age: 31,
    orderType: '注射',
    content: 'セフトリアキソン1g 点滴静注',
    visualIndicator: {
      medicationType: '点滴',
      medicationForm: 'バッグ製剤（100mL）'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 14:00'
  },
  {
    id: 'ORD-018',
    status: '受付済',
    patientId: 'P00012359',
    patientName: '池田 和夫',
    patientKana: 'イケダ カズオ',
    gender: '男',
    birthDate: '1968/07/14',
    age: 57,
    orderType: '病理検査',
    content: '胃生検標本（内視鏡下採取）',
    visualIndicator: {
      tubeType: 'ホルマリン容器',
      tubeColor: '#F59E0B',
      containerType: 'specimen'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 10:30',
    acceptedAt: '2025/10/15 10:45',
    acceptedBy: '看護師A',
    consentRequired: true,
    consentObtained: true
  },
  {
    id: 'ORD-020',
    status: '実施済',
    patientId: 'P00012361',
    patientName: '西村 誠',
    patientKana: 'ニシムラ マコト',
    gender: '男',
    birthDate: '1958/12/03',
    age: 66,
    orderType: '病理検査',
    content: '大腸ポリープ切除標本',
    visualIndicator: {
      tubeType: 'ホルマリン容器',
      tubeColor: '#F59E0B',
      containerType: 'specimen'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/13 09:00',
    acceptedAt: '2025/10/13 09:15',
    acceptedBy: '看護師C',
    implementedAt: '2025/10/13 09:30',
    implementedBy: '臨床検査技師B',
    implementationNotes: '標本を病理検査室へ提出。外部委託（○○病理センター）',
    consentRequired: true,
    consentObtained: true
  },
  {
    id: 'ORD-021',
    status: '指示受済',
    patientId: 'P00012362',
    patientName: '藤井 美和',
    patientKana: 'フジイ ミワ',
    gender: '女',
    birthDate: '1987/05/30',
    age: 38,
    orderType: '細菌検査',
    content: '尿培養・感受性検査',
    visualIndicator: {
      tubeType: '培養ボトル',
      tubeColor: '#10B981',
      containerType: 'culture'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '泌尿器科',
    receivedAt: '2025/10/15 11:00'
  },
  {
    id: 'ORD-022',
    status: '受付済',
    patientId: 'P00012363',
    patientName: '村田 健司',
    patientKana: 'ムラタ ケンジ',
    gender: '男',
    birthDate: '1945/09/12',
    age: 80,
    orderType: '細菌検査',
    content: '喀痰培養・抗酸菌検査',
    visualIndicator: {
      tubeType: '培養ボトル',
      tubeColor: '#10B981',
      containerType: 'culture'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '呼吸器科',
    receivedAt: '2025/10/15 09:00',
    acceptedAt: '2025/10/15 09:15',
    acceptedBy: '看護師D'
  },
  {
    id: 'ORD-024',
    status: '実施済',
    patientId: 'P00012365',
    patientName: '長谷川 隆',
    patientKana: 'ハセガワ タカシ',
    gender: '男',
    birthDate: '1970/03/18',
    age: 55,
    orderType: '細菌検査',
    content: '血液培養（2セット）',
    visualIndicator: {
      tubeType: '培養ボトル',
      tubeColor: '#10B981',
      containerType: 'culture'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/13 13:00',
    acceptedAt: '2025/10/13 13:15',
    acceptedBy: '看護師B',
    implementedAt: '2025/10/13 13:30',
    implementedBy: '臨床検査技師A',
    implementationNotes: '好気・嫌気ボトルに接種。培養器セット。'
  },
  {
    id: 'ORD-027',
    status: '指示受済',
    patientId: 'P00012368',
    patientName: '清水 洋介',
    patientKana: 'シミズ ヨウスケ',
    gender: '男',
    birthDate: '1955/06/08',
    age: 70,
    orderType: '服薬指導',
    content: 'ワーファリン服薬指導（初回処方時）',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '循環器科',
    receivedAt: '2025/10/15 09:15'
  },
  {
    id: 'ORD-028',
    status: '実施済',
    patientId: 'P00012369',
    patientName: '三浦 さくら',
    patientKana: 'ミウラ サクラ',
    gender: '女',
    birthDate: '1990/03/12',
    age: 35,
    orderType: '服薬指導',
    content: '抗生剤服薬指導（適切な服用方法）',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 08:00',
    implementedAt: '2025/10/15 08:30',
    implementedBy: '薬剤師A',
    implementationNotes: '服用回数・タイミング、副作用について説明。理解良好。'
  },
  {
    id: 'ORD-032',
    status: '受付済',
    patientId: 'P00012373',
    patientName: '石井 美咲',
    patientKana: 'イシイ ミサキ',
    gender: '女',
    birthDate: '1982/07/30',
    age: 43,
    orderType: '汎用',
    content: '細菌検査伝票依頼',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 13:30',
    acceptedAt: '2025/10/15 13:45',
    acceptedBy: '看護師A',
    scheduledTime: '14:00'
  },
  {
    id: 'ORD-033',
    status: '指示受済',
    patientId: 'P00012374',
    patientName: '佐々木 優子',
    patientKana: 'ササキ ユウコ',
    gender: '女',
    birthDate: '1975/09/20',
    age: 50,
    orderType: '処置',
    content: '点滴処置',
    allergies: [mockAllergies[0], mockAllergies[1], mockAllergies[4], mockAllergies[6], mockAllergies[7]],
    hasAllergies: true,
    contraindications: [
      {
        id: 'c3',
        type: '特記事項',
        content: '血管確保困難（細い血管）',
        reason: '過去の点滴時に血管確保に時間を要した。穿刺は熟練者が実施すること',
        registeredDate: '2024/05/20',
        source: '看護記録'
      }
    ],
    hasContraindications: true,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 14:30'
  },
  {
    id: 'ORD-034',
    status: '指示受済',
    patientId: 'P00012375',
    patientName: '岡田 翔太',
    patientKana: 'オカダ ショウタ',
    gender: '男',
    birthDate: '1962/04/18',
    age: 63,
    orderType: '内視鏡検査',
    examinationType: '内視鏡検査',
    endoscopyDetails: '気管支鏡検査',
    content: '気管支鏡検査',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '呼吸器科',
    receivedAt: '2025/10/15 13:00',
    scheduledTime: '15:30',
    consentRequired: true,
    consentObtained: true,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 13:00', updatedBy: '呼吸器科医師' }
    ]
  },
  {
    id: 'ORD-035',
    status: '受付済',
    patientId: 'P00012376',
    patientName: '森田 裕子',
    patientKana: 'モリタ ユウコ',
    gender: '女',
    birthDate: '1970/08/22',
    age: 55,
    orderType: '処置',
    content: '腹腔穿刺（腹水採取）',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 10:00',
    acceptedAt: '2025/10/15 10:30',
    acceptedBy: '看護師A',
    scheduledTime: '11:30',
    consentRequired: true,
    consentObtained: false,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 10:00', updatedBy: '田中医師' },
      { status: '受付済', timestamp: '2025/10/15 10:30', updatedBy: '看護師A' }
    ]
  },
  {
    id: 'ORD-036',
    status: '実施済',
    patientId: 'P00012377',
    patientName: '吉田 浩二',
    patientKana: 'ヨシダ コウジ',
    gender: '男',
    birthDate: '1948/11/15',
    age: 76,
    orderType: '処置',
    content: '中心静脈カテーテル挿入',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '外科',
    receivedAt: '2025/10/15 08:00',
    acceptedAt: '2025/10/15 08:30',
    acceptedBy: '看護師B',
    implementedAt: '2025/10/15 09:00',
    implementedBy: '外科医師',
    implementationNotes: 'CVカテーテル挿入完了。右内頸静脈から挿入。',
    scheduledTime: '09:00',
    consentRequired: true,
    consentObtained: true,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 08:00', updatedBy: '外科医師' },
      { status: '受付済', timestamp: '2025/10/15 08:30', updatedBy: '看護師B' },
      { status: '実施済', timestamp: '2025/10/15 09:00', updatedBy: '外科医師' }
    ]
  },
  {
    id: 'ORD-037',
    status: '受付済',
    patientId: 'P00012378',
    patientName: '井上 真由美',
    patientKana: 'イノウエ マユミ',
    gender: '女',
    birthDate: '1985/03/10',
    age: 40,
    orderType: '病理検査',
    content: '乳腺針生検',
    visualIndicator: {
      tubeType: 'ホルマリン容器',
      tubeColor: '#F59E0B',
      containerType: 'specimen'
    },
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '外科',
    receivedAt: '2025/10/15 09:30',
    acceptedAt: '2025/10/15 10:00',
    acceptedBy: '看護師C',
    scheduledTime: '14:00',
    consentRequired: true,
    consentObtained: true,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 09:30', updatedBy: '外科医師' },
      { status: '受付済', timestamp: '2025/10/15 10:00', updatedBy: '看護師C' }
    ]
  },
  {
    id: 'ORD-038',
    status: '指示受済',
    patientId: 'P00012379',
    patientName: '中島 大輔',
    patientKana: 'ナカジマ ダイスケ',
    gender: '男',
    birthDate: '1956/07/05',
    age: 69,
    orderType: '内視鏡検査',
    examinationType: '内視鏡検査',
    endoscopyDetails: '小腸カプセル内視鏡',
    content: '小腸カプセル内視鏡',
    allergies: [],
    hasAllergies: false,
    location: '外来',
    department: '内科',
    receivedAt: '2025/10/15 12:00',
    scheduledTime: '16:00',
    consentRequired: true,
    consentObtained: false,
    statusHistory: [
      { status: '指示受済', timestamp: '2025/10/15 12:00', updatedBy: '消化器科医師' }
    ]
  }
];

export const contraindications: Contraindication[] = [
  {
    id: 'c1',
    medication: 'ペニシリン系抗生物質',
    allergen: 'ペニシリン系抗生物質',
    severity: '禁忌',
    match: true
  },
  {
    id: 'c2',
    medication: '造影剤使用検査',
    allergen: '造影剤',
    severity: '要注意',
    match: false
  }
];

export const medicalHistory = [
  {
    id: 'h1',
    condition: '高血圧症',
    diagnosedDate: '2020/04/01',
    status: '治療継続中'
  },
  {
    id: 'h2',
    condition: '糖尿病（2型）',
    diagnosedDate: '2018/09/15',
    status: '治療継続中'
  }
];